### ISSUE TITLE
SourceBucket no longer exists

### ISSUE THREAD

**Issue by gudlyf** [aws-samples/aws-account-vending-machine#8]
`% aws s3 cp s3://mpsa-reinvent19/resources . --recursive
fatal error: An error occurred (NoSuchBucket) when calling the ListObjectsV2 operation: The specified bucket does not exist`

**Comment by khastation** [comment]
@gudlyf this is the link for the CFN template to launch this solution: https://mpsa-reinvent19-us-east-2.s3.us-east-2.amazonaws.com/AccountCreationLambdaSetup-cfn.yaml
Are you able to access it to deploy this solution?

**Comment by gudlyf** [comment]
No, because the bucket is listed as `SourceBucket` here:

`  SourceBucket:
    Description: "Bucket name of the S3 bucket holding all the files for the Account Vending Machine set up"
    Type: String
    Default: "mpsa-reinvent19"`

**Comment by khastation** [comment]
@gudlyf so in the resources section, the template appends a region parameter while using the bucket name supplied in the parameter:
```
AccountBuilderLambda:
    Type: "AWS::Lambda::Function"
    DependsOn: LambdaExecuteRole
    Properties:
      Handler: "AccountCreationLambda.main"
      Runtime: "python3.6"
      Role: !GetAtt LambdaExecuteRole.Arn
      Timeout: 800
      TracingConfig:
          Mode: "Active"
      Code:
        S3Bucket: !Sub
          - ${Bucket}-${AWS::Region}
          - { Bucket: !Ref SourceBucket }
        S3Key: "AccountCreationLambda.zip"
```
Does that answer your question?
